name: Generate PlantUML diagram

on: [push]

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps: 
     - name: First echo
       run: echo 'First echo !'
     
     - uses: actions/setup-java@v4
     - name: Use java
       run: java -version
